### ISSUE TITLE
Discord.js can crash the bot

### ISSUE THREAD

**Issue by ahoys** [ahoys/discaptcha#5]
If a connection issue emerges in Discord.js, it may cause the entire bot to crash.
```
(node:1616) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 2): DiscordAPIError: Cannot send messages to this user
  root Raunhofer triggered unverified. +15h
  root Raunhofer triggered moderators. +10h
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Client.emit (events.js:163:17)
    at WebSocketConnection.onError (R:\DISCAPTCHA\node_modules\discord.js\src\cl
ient\websocket\WebSocketConnection.js:374:17)
    at WebSocket.onError (R:\DISCAPTCHA\node_modules\ws\lib\event-target.js:128:
16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at _receiver.cleanup (R:\DISCAPTCHA\node_modules\ws\lib\websocket.js:211:14)

    at Receiver.cleanup (R:\DISCAPTCHA\node_modules\ws\lib\receiver.js:557:13)
    at WebSocket.finalize (R:\DISCAPTCHA\node_modules\ws\lib\websocket.js:206:20
)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! discaptcha@1.0.0 start: `node src/discaptcha.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discaptcha@1.0.0 start script 'node src/discaptcha.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discaptcha package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/discaptcha.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discaptcha
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discaptcha
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     R:\DISCAPTCHA\npm-debug.log

```

**Comment by ahoys** [comment]
It can't anymore thanks to threading, but I still have to figure out how to handle situations where the connection is lost even on the 1st attempt.
